### ISSUE TITLE
Where is the combined template for cutting? 

### ISSUE THREAD

**Issue by atomicwrites** [nooges/lets-split-v2-case#1]
There are svg files for the spparate layers and a png named preview.png of all the layers ready to cut but no svg.

**Comment by nooges** [comment]
The combined template is in `sandwich-split.eps`, as I normally use Adobe Illustrator to edit, and its SVG export abilities sometimes has issues. Ponoko prefers EPS files over SVG when Illustrator is used, as it preserves size info better. Anyhow, I've added `sandwich-split.svg` to the repo.
